name: EconomyAPI
version: '${project.version}'
main: me.vineer.economyapi.EconomyAPI
api-version: 1.16
authors: [ Vineer ]
loadbefore: [PlayerManager]
depend:
  - PlaceholderAPI
commands:
  money:
    description: your money
    usage: /<command>
